---
solana_user: solana
solana_home: "/home/{{ solana_user }}"
secrets_path: "{{ solana_home }}/.secrets"
env_path: "{{ solana_home }}/.local/share/solana/install/active_release/bin"
rpc_port: 8899
rpc_bind_address: 0.0.0.0
dynamic_port_range: 8000-10000
expected_genesis_hash: 5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d
jito:
  enabled: True
  tip_payment_program_pubkey: T1pyyaTNZsKv2WcRAB8oVnk93mLJw2XzjtVYqCsaHqt
  tip_distribution_program_pubkey: 4R3gSG8BpU4t19KYj8CfnbtRpnT8gtk4dvTHxVRwc2r7
  merkle_root_upload_authority: GZctHpWXmsZC1YHACTGGcHhYxjdRqQvTpYkb9LMvxDib
  commission_bps: 800
  block_engine_url: https://ny.mainnet.block-engine.jito.wtf
  shred_receiver_address: 141.98.216.96:1002