---
- name: 🚫 Install fail2ban package
  package:
    name:
      - fail2ban
    state: present

- name: 🚫 Create jail.local
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    mode: 0644
    owner: root
    group: root

- name: 🚫 Restart fail2ban
  systemd:
    name: fail2ban
    state: restarted