---
- name: create download dir
  become: yes
  file:
    path: /tmp/solana
    state: directory
    owner: "{{ solana_user }}"
    group: "{{ solana_user }}"

- name: install solana
  block:
    - name: download latest solana release installer
      get_url:
        url: "https://release.anza.xyz/v{{ solana_version | default('stable') }}/install"
        dest: /tmp/solana/
        mode: 0755
    - name: run solana installer
      shell: /tmp/solana/install
  become: yes
  become_user: "{{ solana_user }}"
  become_method: sudo


- name: remove installer
  file:
    path: /tmp/solana
    state: absent
