- name: Install a list of packages
  become: true
  become_user: root
  apt:
    update_cache: yes
    pkg:
      - libssl-dev
      - libudev-dev
      - pkg-config
      - zlib1g-dev
      - llvm
      - clang
      - cmake
      - make
      - libprotobuf-dev
      - protobuf-compiler

- name: check if cargo is installed
  become: true
  become_user: "{{ solana_user }}"
  become_method: sudo
  shell: "test -f {{ solana_home }}/.cargo/env && source {{ solana_home }}/.cargo/env && command -v cargo"
  args:
    executable: /bin/bash
  register: cargo_exists
  ignore_errors: yes

- name: Download Installer
  when: cargo_exists is failed
  become: true
  become_user: "{{ solana_user }}"
  become_method: sudo
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'

- name: install rust/cargo
  become: true
  become_user: "{{ solana_user }}"
  become_method: sudo
  when: cargo_exists is failed
  shell: /tmp/sh.rustup.rs -y
  args:
    executable: /bin/bash