---
- name: Create solana validator service
  template:
    src: solana-validator.service.j2
    dest: /etc/systemd/system/solana-validator.service
    mode: 0644
    owner: root
    group: root

- name: Enable solana service
  systemd:
    name: solana-validator
    enabled: yes
    daemon_reload: yes
