---

- name: 🐸 Create secrets dir
  become: yes
  file:
    path: /home/solana/.kolibrio
    state: directory
    mode: '0700'
    owner: solana


- name: jito relayer repository
  become: true
  become_user: solana
  git:
    repo: "https://github.com/jito-foundation/jito-relayer.git"
    dest: /home/solana/jito-relayer
    version: v0.3.1
    recursive: yes
    update: yes
    clone: yes
  tags:
    - jito-relayer.install

- name: build relayer
  become: true
  become_user: solana
  shell: source /home/solana/.cargo/env && cargo build --release -j 4
  args:
    chdir: /home/solana/jito-relayer
    executable: /bin/bash
  tags:
    - jito-relayer.install

- name: Create jito-relayer service
  template:
    src: jito-relayer.service.j2
    dest: /etc/systemd/system/jito-relayer.service
    mode: 0644
    owner: root
    group: root
  tags:
    - jito-relayer.install

- name: Reload systemd
  systemd:
    daemon_reload: yes
  tags:
    - jito-relayer.install

- name: Enable jito-relayer service
  systemd:
    name: jito-relayer
    enabled: yes
  tags:
    - jito-relayer.install
